[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "hajime-ui"
version = "0.1.0"
description = "Bibliothèque de composants Django Cotton + Tailwind CSS + HTMX + Alpine.js"
requires-python = ">=3.11"
dependencies = [
    "django>=4.2",
    "django-cotton>=0.9",
]

[project.urls]
Homepage = "https://github.com/yanis-san/hajime-ui"

[tool.setuptools.packages.find]
where = ["."]
include = ["hajime_ui*"]

[tool.setuptools.package-data]
"hajime_ui" = ["templates/**/*.html"]
